FROM oven/bun:alpine AS build

RUN mkdir /build
WORKDIR /build

COPY package*.json ./
COPY bun.lockb ./

RUN bun install

COPY . .

RUN bun run build

FROM nginx:alpine AS deploy

COPY --from=build /build/dist /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]