# Generated by Django 5.1.1 on 2025-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='requires_explanation',
            field=models.BooleanField(default=False),
        ),
    ]
