import BFI2SClassicGettingStartedSection from "@/components/sections/bfi2s_classic/GettingStartedSection";
import BFI2SClassicWhatToExpectSection from "@/components/sections/bfi2s_classic/WhatToExpectSection";
import BFI2SClassicThankYouForParticipatingSection from "@/components/sections/bfi2s_classic/ThankYouForParticipatingSection";
import BFI2SAvatarGettingStartedSection from "@/components/sections/bfi2s_avatar/GettingStartedSection";
import BFI2SAvatarWhatToExpectSection from "@/components/sections/bfi2s_avatar/WhatToExpectSection";
import BFI2SAvatarThankYouForParticipatingSection from "@/components/sections/bfi2s_avatar/ThankYouForParticipatingSection";
import CFQClassicGettingStartedSection from "@/components/sections/cfq_classic/GettingStartedSection";
import CFQClassicWhatToExpectSection from "@/components/sections/cfq_classic/WhatToExpectSection";
import CFQClassicThankYouForParticipatingSection from "@/components/sections/cfq_classic/ThankYouForParticipatingSection";
import CFQAvatarGettingStartedSection from "@/components/sections/cfq_avatar/GettingStartedSection";
import CFQAvatarWhatToExpectSection from "@/components/sections/cfq_avatar/WhatToExpectSection";
import CFQAvatarThankYouForParticipatingSection from "@/components/sections/cfq_avatar/ThankYouForParticipatingSection";

export const AVATARS = [
  {
    pose_id: "SilasHR_public",
    pose_name: "Silas",
    gender: "male",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/582ee8fe072a48fda3bc68241aeff660_45660/preview_target.webp",
    default_voice: {
      free: "5c837919d188407cac1ea65a8889e496",
      premium: "5c837919d188407cac1ea65a8889e496",
      selected: "5c837919d188407cac1ea65a8889e496",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1732855092,
    share_code: "",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "cdb979191b0c4cdf974bf9c9305f9d7b",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
  {
    pose_id: "Shawn_Therapist_public",
    pose_name: "Shawn",
    gender: "male",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/db2fb7fd0d044b908395a011166ab22d_45680/preview_target.webp",
    default_voice: {
      free: "606c9d2a08be4e4f8cb38eafef8090de",
      premium: "606c9d2a08be4e4f8cb38eafef8090de",
      selected: "606c9d2a08be4e4f8cb38eafef8090de",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1732855256,
    share_code: "",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "177ea67376364fbfb5dbc1f304f4916a",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
  {
    pose_id: "Ann_Therapist_public",
    pose_name: "Ann",
    gender: "female",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/75e0a87b7fd94f0981ff398b593dd47f_45570/preview_talk_4.webp",
    default_voice: {
      free: "2e4de8a01f3b4e9c96794045e2f12779",
      premium: "2e4de8a01f3b4e9c96794045e2f12779",
      selected: "6eafa43fdc16437b8f5abe512cc2b3cf",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1732855717,
    share_code: "",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "153201a3d6984f7c8323134b6d494410",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
  {
    pose_id: "Wayne_20240711",
    pose_name: "Wayne",
    gender: "male",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/a3fdb0c652024f79984aaec11ebf2694_34350/preview_target.webp",
    default_voice: {
      free: "",
      premium: "",
      selected: "2411aaf820874397a44530f94032bfdc",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1727136000,
    share_code: "b41ce784-b86b-4437-83f5-9a53416e6f8a",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "demo-1",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
  {
    pose_id: "Judy_Teacher_Sitting_public",
    pose_name: "Judy",
    gender: "female",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/68fbd9f64a4948baa3c295d35f49b61c_45630/preview_target.webp",
    default_voice: {
      free: "7ffb69e578d4492587493c26ebcabc31",
      premium: "7ffb69e578d4492587493c26ebcabc31",
      selected: "7ffb69e578d4492587493c26ebcabc31",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1732855119,
    share_code: "",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "87884edb6e014aa7b2916e3656ffb3cb",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
  {
    pose_id: "June_HR_public",
    pose_name: "June",
    gender: "female",
    status: "ACTIVE",
    is_public: true,
    normal_preview: "https://files2.heygen.ai/avatar/v3/74447a27859a456c955e01f21ef18216_45620/preview_talk_1.webp",
    default_voice: {
      free: "68dedac41a9f46a6a4271a95c733823c",
      premium: "68dedac41a9f46a6a4271a95c733823c",
      selected: "68dedac41a9f46a6a4271a95c733823c",
    },
    need_remove_background: false,
    is_new: false,
    created_at: 1732855106,
    share_code: "",
    msg: "",
    detailed_msg: null,
    queue_size: null,
    knowledge_base_id: "6496186220f541d5b19afed1518c9885",
    is_embed_paid: null,
    is_share_paid: null,
    is_expired: false,
  },
];

export const STT_LANGUAGE_LIST = [
  { label: "Bulgarian", value: "bg", key: "bg" },
  { label: "Chinese", value: "zh", key: "zh" },
  { label: "Czech", value: "cs", key: "cs" },
  { label: "Danish", value: "da", key: "da" },
  { label: "Dutch", value: "nl", key: "nl" },
  { label: "English", value: "en", key: "en" },
  { label: "Finnish", value: "fi", key: "fi" },
  { label: "French", value: "fr", key: "fr" },
  { label: "German", value: "de", key: "de" },
  { label: "Greek", value: "el", key: "el" },
  { label: "Hindi", value: "hi", key: "hi" },
  { label: "Hungarian", value: "hu", key: "hu" },
  { label: "Indonesian", value: "id", key: "id" },
  { label: "Italian", value: "it", key: "it" },
  { label: "Japanese", value: "ja", key: "ja" },
  { label: "Korean", value: "ko", key: "ko" },
  { label: "Malay", value: "ms", key: "ms" },
  { label: "Norwegian", value: "no", key: "no" },
  { label: "Polish", value: "pl", key: "pl" },
  { label: "Portuguese", value: "pt", key: "pt" },
  { label: "Romanian", value: "ro", key: "ro" },
  { label: "Russian", value: "ru", key: "ru" },
  { label: "Slovak", value: "sk", key: "sk" },
  { label: "Spanish", value: "es", key: "es" },
  { label: "Swedish", value: "sv", key: "sv" },
  { label: "Turkish", value: "tr", key: "tr" },
  { label: "Ukrainian", value: "uk", key: "uk" },
  { label: "Vietnamese", value: "vi", key: "vi" },
];

export const SECTION_KEYS = {
  CHOOSE_YOUR_AVATARS: ["bfi2s_avatar_choose_your_avatar", "cfq_avatar_choose_your_avatar"],
  MICROPHONE_CHECK: ["bfi2s_avatar_mic_check", "cfq_avatar_mic_check"],
};

export const SECTION_MAP: Record<string, Record<string, React.ReactElement>> = {
  bfi2s_classic: {
    bfi2s_classic_getting_started: <BFI2SClassicGettingStartedSection />,
    bfi2s_classic_what_to_expect: <BFI2SClassicWhatToExpectSection />,
    bfi2s_classic_thank_you_for_participating: <BFI2SClassicThankYouForParticipatingSection />,
  },
  bfi2s_avatar: {
    bfi2s_avatar_getting_started: <BFI2SAvatarGettingStartedSection />,
    bfi2s_avatar_what_to_expect: <BFI2SAvatarWhatToExpectSection />,
    bfi2s_avatar_thank_you_for_participating: <BFI2SAvatarThankYouForParticipatingSection />,
  },
  cfq_classic: {
    cfq_classic_getting_started: <CFQClassicGettingStartedSection />,
    cfq_classic_what_to_expect: <CFQClassicWhatToExpectSection />,
    cfq_classic_thank_you_for_participating: <CFQClassicThankYouForParticipatingSection />,
  },
  cfq_avatar: {
    cfq_avatar_getting_started: <CFQAvatarGettingStartedSection />,
    cfq_avatar_what_to_expect: <CFQAvatarWhatToExpectSection />,
    cfq_avatar_thank_you_for_participating: <CFQAvatarThankYouForParticipatingSection />,
  },
};

export const VIOLATION_RESPONSES = ["I didn't quite get that. Try to be more verbose and keep it on point."];
